### ISSUE TITLE
hi love your work

### ISSUE THREAD

**Issue by data-and-troi** [jakealbaugh/jake.fun#2]
Hi there, I love your projects. I made a short art video re: chat gpt that I'm going to put on youtube that realistically will get like 20 views. I used your Musical Chord Progression Arpeggiator(https://codepen.io/jak_e/pen/qNrZyw) to score it. Are you OK with this? Would you like to be cited or linked to when I put it up? I can show you the video if you like before I put it up! You can write me back here: brianna.barnes.writer@protonmail.com. Thank you! Brianna

**Comment by ja-k-e** [comment]
Thanks so much for reaching out Brianna! It makes me so glad to hear that things like this are useful for others. You ABSOLUTELY can use my work to do things like this. If you want to cite me, feel free, but you do not have to all. I will send an email. Thanks again, can't wait to see it!

**Comment by data-and-troi** [comment]
Hi, so sorry to respond here instead of my email--I did get your email, thank you, but I can't find it to save my life. I did post the videos! Only 8 months later! I cited you in the description! Please let me know if you would like to be taken off, etc. Thank you again!! yr fan, Brianna 

vid 1 https://www.youtube.com/watch?v=DQtYUB_-LjY

vid 2 https://www.youtube.com/watch?v=z_TvRecDRTw
